### ISSUE TITLE
Startup customization when 'enqueue' a cleaml task for cleaml-agent

### ISSUE THREAD

**Issue by Muscle-Oliver** [allegroai/clearml-agent#114]
Hello,
Appreciate for any help or guidance for my situation!

Now I'm going through the following procedure:

(With a self-hosted clearml server in a local kubernetes)
1. Run a task locally, which reaults can be seen in clearml web UI;
2. Make a clone of this task, and `enqueue` this task in web UI;
3. `clearml-agent` creates a k8s pod from the default base docker image, `apt install` some pkgs, then creates a virtual env and `pip install` required pkgs, finally runs the task.

Here is the problem:
Since my poor internet connection, the startup procedure is time consuming and fails frequently.
Then I'm trying to pre-install all env requirements inside a docker image, for `clearml-agent` to run task scripts directly after pod startup. (I put a conda env folder into the docker image)

But I cannot find a way to override the default env creation or skip the online pkg installation.

I tried modifying the task execution settings, including the startup docker IMAGE and the SETUP SHELL SCRIPT.

The modified docker image have the env I previously prepared, but `clearml-agent` always starts the k8s pod with something as:
`bash echo -c <base64cypher> | base64 --decode >> ~/__start_agent__.sh ; /bin/bash ~/__start_agent__.sh ; exit 0`
with SETUP SHELL SCRIPT inserted in the `__start_agent__.sh` file.

Can I have a way to customize this `__start_agent__.sh` by any means, in order to skip the default env creation and use my own conda env instead?

Appreciate for any help!

**Comment by jkhenning** [comment]
Hi @Muscle-Oliver ,

I think you're looking for the `CLEARML_AGENT_SKIP_PYTHON_ENV_INSTALL` environment variable which will cause the agent to assume everything is installed and just try to use python to run the task

**Comment by Muscle-Oliver** [comment]
Hi @jkhenning ,
Thanks for the quick reply!
I tried out the `CLEARML_AGENT_SKIP_PYTHON_ENV_INSTALL` and the `CLEARML_AGENT_SKIP_PIP_VENV_INSTALL`, which is helpful skipping the creation of venv! 👍 

But the `apt update` and `apt install` still remain in `__start_agent__.sh`.
As I'm using a pre-prepared docker image (with complete apt and pip environment), is there a way to skip those `apt` commands as well?
(Went through `clearml-agent/definitions.py` but found no clue about `apt`)

Appreciate for any help, again!

**Comment by jkhenning** [comment]
Hi @Muscle-Oliver ,

This can be controlled using the `K8sIntegration` class' init method's `container_bash_script` argument (which by default uses the script found in `K8sIntegration.CONTAINER_BASH_SCRIPT`).
However that's not part of the current command line interface, so to change this you will need to modify the `k8s_glue_example.py` file in the image and add an option to override this.
Hope that helps 🙂
