### ISSUE TITLE
bug with custom agent services build

### ISSUE THREAD

**Issue by InCogNiTo124** [allegroai/clearml-agent#140]
(continuation of https://clearml.slack.com/archives/CTK20V944/p1676473286252319?thread_ts=1676473286.252319&cid=CTK20V944)

Hello,

if I build this https://github.com/allegroai/clearml-agent/tree/master/docker/services from scratch, and run the resulting container, it fails with `syntax error at line 20`.

I suggest switching from `#!/usr/sh` to `#!/usr/bash`.

**Comment by InCogNiTo124** [comment]
The reason for custom building is bumping the base image from `ubuntu:18.04` to `ubuntu:22.04`

**Comment by jkhenning** [comment]
@InCogNiTo124 sounds like a good idea 🙂 - care to add a PR?

**Comment by InCogNiTo124** [comment]
@jkhenning have you found time to look at the PR?

**Comment by jkhenning** [comment]
Done, sorry for the delay 🙏
