### ISSUE TITLE
Tasks initialized by a HyperParameterOptimizer (on an agent) does not upload artifacts to fileserver

### ISSUE THREAD

**Issue by mads-oestergaard** [allegroai/clearml-agent#144]
When executing a hyperparameter sweep where the optimization process is run as a service, spawned subtasks does not upload artifacts correctly to the file server. 

Instead, we get a path to a local directory on whatever machine runs the agent like `file:///data/clearml/venvs-builds/3.9/task_repository/our-repo/logs/` instead of `http://clearml.our-server.com:8081/...`

I have followed the [official guide on optimization](https://clear.ml/docs/latest/docs/guides/optimization/hyper-parameter-optimization/examples_hyperparam_opt/), with the exception that I create the base task as a draft instead of actually running it.

Package versions:
clearml @ 1.9.3
clearml-agent @ 1.5.1

**Comment by mads-oestergaard** [comment]
Sure! I'll attach the log of the CPU agent that runs the sweep (sweep-task.log) and the log of one of the GPU agents executing a task scheduled by the sweep runner (sweep-subtask.log). 

[sweep-task.log](https://github.com/allegroai/clearml-agent/files/10984266/sweep-task.log)
[sweep-subtask.log](https://github.com/allegroai/clearml-agent/files/10984269/sweep-subtask.log)

**Comment by jkhenning** [comment]
@mads-oestergaard did you specify the `output_uri` parameter of `Task.init()`? (or, alternatively, set up the `sdk.development.default_output_uri` setting in your _clearml.conf_ file)
If these are not specified, models and artifacts will by default be stores into the local storage.

**Comment by mads-oestergaard** [comment]
The optimization task was not initialized with `output_uri` set, but it does seem to upload plots correctly: 
```
# Initialize the clearml task
    task = clearml.Task.init(
        project_name=cfg.clearml.project_name,
        task_name="Automatic Hyper-Parameter Optimization",
        task_type=clearml.Task.TaskTypes.optimizer,
        reuse_last_task_id=False,
    )
```
I created the base task like this:
```
def generate_base_task_id(experiment: str) -> str:
    """Create a task (in draft) and return the ID of the created task"""
    task: Task = Task.create(
        "Optimization/base_tasks",
        task_name=experiment,
        script="src/hydra_train.py",
    )
    task.connect({"+experiment": experiment, "project_name": "tmp"}, "Hydra")
    return task.id
```

`Task.init()` sets the `output_uri` parameter in `hydra_train.py`. Could it be caused by `add_task_init_call` being True by default in `Task.create()`?

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @mads-oestergaard ! Note that the optimizer task and the task you want to optimized are treated completely separate. So any change you do in the optimizer (like adding an `output_uri`) will not reflect in the task you want to optimize.

I suggest you initialize the task you want to optimize with `Task.init`, and specify the `output_uri` in that `init` call.
Or, you could try setting the `CLEARML_DEFAULT_OUTPUT_URI` env var to the desired `output_uri`, or set `sdk.development.default_output_uri` in your `clearml.conf`.
