### ISSUE TITLE
Torch wheel resolution broken for torch==1.11.0 and cuda 117

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml-agent#152]
Hi,

In clearml-agent==1.5.2, if I specify in the requirements: `torch==1.11.0` and the agent recognises cuda 117 (`agent.cuda_version = 117` is printed in the logs),
The agent will download the cpu version of torch 1.11.0 instead of trying to downgrade the cuda version and find the matching wheel (eg. 1.11.0+cuda117 -> 1.11.0+cuda116 -> 1.11.0+cuda115 exists)

**Comment by jkhenning** [comment]
Hi @H4dr1en, can you attach the logs please?

**Comment by jkhenning** [comment]
@H4dr1en updating from the Slack discussion:
See at the attached images
https://download.pytorch.org/whl/cu117/torch/ does not contain a specific wheel for cuda117 to x86, they use the pip default one
![Screenshot from 2023-05-11 1](https://github.com/allegroai/clearml-agent/assets/59198928/dad12dc4-0f2b-49ab-a2f1-af9f241c351d)
![Screenshot from 2023-05-11 2](https://github.com/allegroai/clearml-agent/assets/59198928/ac6d0006-cccf-46ee-8fea-d06a887a8c83)

**Comment by H4dr1en** [comment]
More on the Slack discussion > https://clearml.slack.com/archives/CTK20V944/p1683734024785499
