### ISSUE TITLE
ClearML Colab Urllib3 problem

### ISSUE THREAD

**Issue by dberkerdem** [allegroai/clearml-agent#153]
[Colab notebook](https://github.com/allegroai/clearml/blob/master/examples/clearml_agent/clearml_colab_agent.ipynb) for clearml-agent raises error when a new task is submitted due to the new release (2.0.2) of Urllib3 library.
![image](https://user-images.githubusercontent.com/72249178/236431747-5aef6bc6-d6ee-4b83-a537-16c8767fa0d3.png)

**Comment by jkhenning** [comment]
Hi @dberkerdem , ClearML SDK v1.10.4rc1 should fix this issue. An official version will be released next week.

**Comment by dberkerdem** [comment]
ClearML SDK v1.10.4rc1 works great, thank you!
