### ISSUE TITLE
Cloned experiment ignores arguments

### ISSUE THREAD

**Issue by copper-ctl** [allegroai/clearml-agent#170]
In the cloned experiment, arguments appear under the configuration tab but are not used during task run. Task data under the info tab also seems partial:
![image](https://github.com/allegroai/clearml-agent/assets/12835176/8d075e12-bb69-48e1-85a5-b9ff9f6c6d68)

**Comment by ainoam** [comment]
@copper-ctl Missing some information here: What's the status of the task in question? What are you missing in the info tab? What configuration parameters were present originally and ignored? Which ClearML versions are you using?

**Comment by copper-ctl** [comment]
Status of task is: completed.
What is missing in the info tab: all fields below ID. Example attached
![image](https://github.com/allegroai/clearml-agent/assets/12835176/4487473e-f337-4622-9f21-801a2863ac98)
ClearML version: 1.7.2

**Comment by ainoam** [comment]
@copper-ctl What about clearml server and agent versions? Any difference in console log between original and cloned execution?

**Comment by copper-ctl** [comment]
clearml-agent: v1.6.1
clearml-server: not sure what you are referring to. api.version = 1.5
changes in console log: The main difference I see is in arguments not being present.

This problem is new for this server. Previously an agent (v1.5.1) was run on a different machine and no such problems were present. The main differences between the two cases:
1. clearml-server ip has changed
2. clearml-agent version changed
3. Previously the agent was run on a host at the same local network as the server. Currently the agent is run on a machine in a different local network but has access to the server via VPN.

**Comment by copper-ctl** [comment]
I recreated the virtual environment and re-ran the agent and the problem seems to be resolved. Still unsure what was the exact problem. Thanks.
