### ISSUE TITLE
Does clearml-agent caches experiments docker-enviroment?

### ISSUE THREAD

**Issue by konstantinator** [allegroai/clearml-agent#202]
Hello everyone!

I encountered a similar problem [issue](https://github.com/allegroai/clearml-agent/issues/18) but with Docker. Every time I launch a task, I have to wait 5-10 minutes for the environment to build. Is there a way to reuse an already created environment from previous tasks?

Here's how I launch the agent:

`clearml-agent daemon --queue hello_queue --docker my_hello_image`

And here's how I start a task for it:

```
clearml-task --project Hello --name hello --script ./hello_world.py --packages "pip" --queue hello_queue \
  --docker my_hello_image --docker_args "-v /data:/data \
  --rm --name my_container_hello" 
```

**Comment by jkhenning** [comment]
Hi @konstantinator, you can simply achieve that by mounting the `/root/.clearml` from inside the container to the host machine, so basically adding something like: `-v ~/agent/.clearml:/root/.clearml` to the docker args

**Comment by konstantinator** [comment]
Thank you, @jkhenning ! The issue was the lengthy installation of Linux packages on top of my Docker image. I noticed that they were being installed every time the Docker container was launched, so I rebuilt the image with these packages included. Now, the clearml-agent begins executing tasks in less than a minute, which is acceptable for me.

Thank you for your response!
