### ISSUE TITLE
Support UV package manager

### ISSUE THREAD

**Issue by Ruhrozz** [allegroai/clearml-agent#214]
AFAIK [uv](https://github.com/astral-sh/uv) is the fastest package manager now and can be used instead of pip:
```bash
# before
pip install clearml-agent
# after
uv pip install clearml-agent
```
Is there any option to implement uv support?

**Comment by Ruhrozz** [comment]
I think replacing `pip` with `uv pip` everywhere might cover most commands

**Comment by ainoam** [comment]
@Ruhrozz That would definitely be a welcome addition. Would you care to PR it?
Since clearml (and clearml-agent) basically uses `python -m pip`, the simple way to go about it would probably be to override the pip command.

**Comment by mads-oestergaard** [comment]
+1

I would love to see this in clearml. Especially as an alternative to poetry as package manager, it would be great to be able to set `package_manager: uv` in the agent config similar to how its done with poetry today.

**Comment by jkhenning** [comment]
@mads-oestergaard @Ruhrozz clearml-agent v1.9.3rc0 was just released with the UV support - please check it out 🙂

**Comment by marisancans** [comment]
Is uv package manager using cache?
All of my pip packages are always fully re-downloaded

**Comment by mads-oestergaard** [comment]
> @mads-oestergaard @Ruhrozz clearml-agent v1.9.3rc0 was just released with the UV support - please check it out 🙂

Just tried it out - works like a charm 👍 
Thanks for testing and merging

**Comment by alexeyda** [comment]
where should I add UV_CACHE_DIR variable?
