### ISSUE TITLE
Multiple config files

### ISSUE THREAD

**Issue by nirraviv** [allegroai/clearml-agent#41]
Hi,
I'm have multiple projects, some with `pip` and some with `conda` as package manager.
Is there a way to have multiple config files and define the relevant config for each queue?

**Comment by bmartinn** [comment]
Hi @nirraviv 
For some reason this issue was never addressed, my apologies :(
Is your use case similar to [clearml #304](https://github.com/allegroai/clearml/issues/304)
Wouldn't it be easier to configure from code?
WDYT?

**Comment by nirraviv** [comment]
@bmartinn 
It indeed seems similar.
How you would configure it from code if you need to queue beforehand?
I thought maybe you should add as argument an optional config file (default will be `clearml.conf`) to `clearml-agent daemon ...`
This way you can configure different options to each queue.
WDYT?

**Comment by bmartinn** [comment]
@nirraviv selecting a different configuration file is supported:
``` python
import os 
os.environ['CLEARML_CONFIG_FILE'] = `path_to_config`
from clearml import Task
```
But I was actually thinking of just controling the python package analysis option (static / pip freeze / conda) from code.
This seems like the main use case for both issues, no ?

**Comment by nirraviv** [comment]
@bmartinn great. Both seems suitable for me, thanks.

**Comment by bmartinn** [comment]
Sounds good, I'll keep updating in [clearml #304](https://github.com/allegroai/clearml/issues/304)
