### ISSUE TITLE
clearml_agent: ERROR: It is required that you pass in a value for the "algorithms" argument when calling decode().

### ISSUE THREAD

**Issue by joekadi** [allegroai/clearml-agent#46]
When executing command "clearml-agent daemon --queue default" to start an agent running tasks from the default cue, I get a weird error: "clearml_agent: ERROR: It is required that you pass in a value for the "algorithms" argument when calling decode()". This makes no sense as it working fine yesterday and this seems be an Azure error msg. I am using the free-tier-hosted clearML dashboard and running on MBP M1. Can anyone point me in direction of a fix? Thanks

**Comment by jkhenning** [comment]
Hi @joekadi ,
This error is related to a new major version of the PyJWT package used by the ClearML Agent.
The requirements used by the latest version make sure this will not happen - what Agent version are you using?

**Comment by joekadi** [comment]
I updated and it's now working fine! Thanks very much for the swift response.
