### ISSUE TITLE
K8S Glue does not take in env in --template-yaml 

### ISSUE THREAD

**Issue by jax79sg** [allegroai/clearml-agent#51]
https://github.com/allegroai/clearml-agent/blob/cb6bdece39751eaef975287609b8bab603f116e5/clearml_agent/glue/k8s.py#L395
The issue is this line. Setting env:[] will override any env variables from template yaml in the merge_dict later on in the script.
Removing the item will resolve this issue although i'm not sure of the original intent of this entry.

**Comment by jkhenning** [comment]
Hi @jax79sg,

A fix was just pushed to the repo - can you try again and let me know if it works for you?

**Comment by jax79sg** [comment]
Hi, is this push reflected in the pypa wheel clearml-agent==0.17.2? Didn't seem to make any difference.

**Comment by jkhenning** [comment]
Hi @jax79sg, no, this was still not released as an agent version.
You can install the agent directly from the repository using `pip install git+https://github.com/allegroai/clearml-agent.git`

**Comment by jax79sg** [comment]
looks like its fixed. thanks.
