### ISSUE TITLE
k8s glue wants to install torch 1.8.0 and fails

### ISSUE THREAD

**Issue by jax79sg** [allegroai/clearml-agent#52]
Hi, i am running a k8s glue on a disconnected on-prem env. I have a private pypa repo which is pointed to via /etc/pip.conf in the container images. When i submit a task with tensorflow code, on a nvcr.io/cuda10.1-tensorflow image with a requirements.txt without any reference to torch or torchvision, i encountered the following error.

```
clearml_agent: Warning: could not resolve python wheel replacement for torch==1.8.0
clearml_agent: ERROR: Exception when trying to resolve python wheel: Could not find pytorch wheel URL for: torch==1.8.0 with cuda 101 support.
```
First question is why is it even installing torch in the first place?
Second question is what is it trying to resolve to? Is it to pytorch website? I'm on a disconnected env.

**Comment by jax79sg** [comment]
The problem is resolved by doing a git push. Somehow the git diff didn't capture the difference in requirements.txt.

**Comment by Shaked** [comment]
How did you fix this? I'm trying to change the docker image through the UI and I keep getting this error:

> clearml_agent: ERROR: Could not find task id=3082236692364eb9bdd858fa518ec9e1 (for host: )

I also tried to use a completely fresh task (and still changing the docker image through the UI) but it fails
