### ISSUE TITLE
ClearML-Agent using wrong location for venv when using poetry as a package manager

### ISSUE THREAD

**Issue by jan-zajac** [allegroai/clearml-agent#57]
When cloning a task for running on the clearml-agent, the `poetry.lock` file is picked up fine from the git repository and all the packages installed correctly into the location:` /home/ubuntu/.clearml/venvs-builds.1/3.8/task_repository/repository_name/.venv` . (As per clearml-agent logs)

But when running the given task, the virtual environment clearml uses is in` /home/ubuntu/.clearml/venvs-builds.1/3.8/bin  ` which doesn't have any of the dependencies in it.

I've ssh'd into the instance running clearml-agent and verified this is indeed the case.

**Comment by jkhenning** [comment]
Hi @jan-zajac, apologies for only getting to this now 🙁  - we'll take a look and try to reproduce - will update soon...

**Comment by bmartinn** [comment]
@jan-zajac confirmed, for some reason the new poetry version cannot be directed to a target folder :(
I think this is what we need to do: https://python-poetry.org/docs/configuration/#virtualenvscreate-boolean
Let me play around with it and update...

**Comment by jkhenning** [comment]
Hi @jan-zajac,

We've just updated the code with a fix for the this issue, can you please see if it works for you? To test, simply install ClearML Agent directly from the repository's master using  `pip install git+https://github.com/allegroai/clearml-agent.git`

**Comment by jan-zajac** [comment]
Hi @bmartinn @jkhenning. Just tested the with the update and confirm that it has fixed my issue, thank you :)

**Comment by jkhenning** [comment]
Hi @jan-zajac, closing this 🙂
