### ISSUE TITLE
virtual environment (venv) path error - cannot be replaced? 

### ISSUE THREAD

**Issue by Shaked** [allegroai/clearml-agent#61]
I have tried to set a caching disk for venv and generally speaking for most of the agent's installation process. 

This is part of the clearml.conf:

```
   # target folder for virtual environments builds, created when executing experiment
    venvs_dir = /greeneye/clearml/cache/venvs-builds

    # cached virtual environment folder
    venvs_cache: {
        # maximum number of cached venvs
        max_entries: 10
        # minimum required free space to allow for cache entry, disable by passing 0 or negative value
        free_space_threshold_gb: 2.0
        # unmark to enable virtual environment caching
        path: /greeneye/clearml/cache/venvs-cache
    },


    # cached git clone folder
    vcs_cache: {
        enabled: true,
        path: /greeneye/clearml/cache/vcs-cache
    },

    # use venv-update in order to accelerate python virtual environment building
    # Still in beta, turned off by default
    venv_update: {
        enabled: true,
    },

    # cached folder for specific python package download (used for pytorch package caching)
    pip_download_cache {
        enabled: true,
        path: /greeneye/clearml/cache/pip-download-cache
    },

    translate_ssh: true,
    # reload configuration file every daemon execution
    reload_config: false,

    # pip cache folder mapped into docker, used for python package caching
    docker_pip_cache = /greeneye/clearml/cache/pip-cache
    # apt cache folder mapped into docker, used for ubuntu package caching
    docker_apt_cache = /greeneye/clearml/cache/apt-cache

``` 

While running it shows the right directory: 

> agent.venvs_dir = /greeneye/clearml/cache/venvs-builds
agent.venvs_cache.max_entries = 10
agent.venvs_cache.free_space_threshold_gb = 2.0
agent.vcs_cache.enabled = true
agent.vcs_cache.path = /greeneye/clearml/cache/vcs-cache
agent.venv_update.enabled = true
agent.pip_download_cache.enabled = true
agent.pip_download_cache.path = /greeneye/clearml/cache/pip-download-cache
agent.translate_ssh = true
agent.reload_config = false
agent.docker_pip_cache = /greeneye/clearml/cache/pip-cache
agent.docker_apt_cache = /greeneye/clearml/cache/apt-cache
agent.docker_force_pull = false
...
...
Using base prefix '/usr'
New python executable in /greeneye/clearml/cache/venvs-builds/3.6/bin/python3.6
Also creating executable in /greeneye/clearml/cache/venvs-builds/3.6/bin/python
Installing setuptools, pip, wheel...
done.

However, for some reason it fails while looking the previous one:

> Requirement already satisfied: numpy==1.19.2 in /usr/local/lib/python3.6/dist-packages (1.19.2)
PyTorch: requested "torch" version ('==', '1.7.1+cu101'), using pre-installed version 1.7.1+cu101
PyTorch: requested "torchvision" version ('==', '0.8.2+cu101'), using pre-installed version 0.8.2+cu101

> clearml_agent: ERROR: Could not install task requirements!
**[Errno 2] No such file or directory: '/home/jovyan/.clearml/venv-update'**

> Running task 'bc9bf8e753174a249b8d6ac25661676c'
Storing stdout and stderr log to '/tmp/.clearml_agent_out.he3b3x2q.txt', '/tmp/.clearml_agent_out.he3b3x2q.txt'
DONE: Running task 'bc9bf8e753174a249b8d6ac25661676c', exit status 1

Am I missing something?
Shaked

**Comment by bmartinn** [comment]
Hi @Shaked 
The mix is between `venv_update` and `venv_cache` :)
Bottom line you should not have changed the `venv_update`:
```
    # use venv-update in order to accelerate python virtual environment building
    # Still in beta, turned off by default
    venv_update: {
        enabled: false,
    },
```

Background: before we introduced venv folder caching we were trying to use the [venv-update](https://github.com/Yelp/venv-update), although it showed promise it was not able to solve caching for `conda`, so we decided to drop support and move into full venv folder caching. I think we should remove the `venv_update` section from the docs as I believe this is a bit confusing.

**Comment by Shaked** [comment]
@bmartinn I see. I have remvoed `venv_update` and it seems to work. 

>  I think we should remove the venv_update section from the docs as I believe this is a bit confusing.

Sounds like a good idea.
