### ISSUE TITLE
clearML agent run docker container loss clearml.conf

### ISSUE THREAD

**Issue by s1022486** [allegroai/clearml-agent#70]
I run docker mod ,but the job is failed.
this is error message:
--You should consider upgrading via the '/opt/conda/bin/python3.8 -m pip install --upgrade pip' command.
--cp: -r not specified; omitting directory '/root/clearml.conf'

I check clearml-agent-services container, but without find /tmp/.clearml_agent.rtgy84ye.cfg.
Could help me ?
thanks

**Comment by s1022486** [comment]
I do [ clearml-agent init ], and find new confg.
But docker -v /tmp/.clearml_agent.ddz032r2.cfg:/root/clearml.conf is not working

**Comment by jkhenning** [comment]
Hi @s1022486,

It seems that for some reason the file is mounted as a directory

> But docker -v /tmp/.clearml_agent.ddz032r2.cfg:/root/clearml.conf is not working

Where did you see this mount exactly?

**Comment by s1022486** [comment]
> Hi @s1022486,
> 
> It seems that for some reason the file is mounted as a directory
> 
> > But docker -v /tmp/.clearml_agent.ddz032r2.cfg:/root/clearml.conf is not working
> 
> Where did you see this mount exactly?

I found ans, thanks.

when I build clearml-agent container, I without mount local /root/tmp/ folder.

So,I mount local /root/tmp/ folder to clearml-agent container, done.

**Comment by jkhenning** [comment]
Hi @s1022486, can we close this issue?

**Comment by s1022486** [comment]
Yes,thanks you email.
=================================
麗臺科技 專案一部
專案工程師 羅世軒-Kevin,Lo

電子信箱 : ***@***.***
=================================


Jake Henning ***@***.***> 於 2021年7月14日 週三 下午6:12寫道：

**Comment by s1022486** [comment]
> I run docker mod ,but the job is failed.
> this is error message:
> --You should consider upgrading via the '/opt/conda/bin/python3.8 -m pip install --upgrade pip' command.
> --cp: -r not specified; omitting directory '/root/clearml.conf'
> 
> I check clearml-agent-services container, but without find /tmp/.clearml_agent.rtgy84ye.cfg.
> Could help me ?
> thanks

**Comment by KhanMechAI** [comment]
Im having the same issue, but i dont quite understand the solution. Does anyone have any more clarity?

**Comment by david-nano** [comment]
> Im having the same issue, but i dont quite understand the solution. Does anyone have any more clarity?

The case here was the file binding, the `clearml.conf` is mounted as a folder and not as a file.
In my case, I've exec into the container and read the file correctly, but I still got the error. Anyone?
