### ISSUE TITLE
Poetry docker agent - cache venv and packages

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml-agent#74]
Copied from Slack: https://clearml.slack.com/archives/CTK20V944/p1628255232238300

It appears that when I use poetry in a docker agent, it recreates the environment (doesn't persist the venv) and redownloads all the python packages (doesn't use a cache).  Is this how the system currently works, or are there specific flags and such that I have not enabled to use the cache and persist the venv for poetry?  Should I map the poetry cache volume to a location on the host?

Response from @bmartinn 
Yes, this will solve it! (maybe we should have that automatically if using poetry as package manager).
Meanwhile you can add the mapping here:
https://github.com/allegroai/clearml-agent/blob/bd411a19843fbb1e063b131e830a4515233bdf04/docs/clearml.conf#L137
extra_docker_arguments: ["-v", "/mnt/cache/poetry:/root/poetry_cache_here"]

**Comment by johnml1135** [comment]
This solution should both save the cached packages and virtual environments.  On windows it would be:
extra_docker_arguments: ["-v", "C:\Users\<user name>\AppData\Local\pypoetry\Cache: ~/.cache/pypoetry"]

https://python-poetry.org/docs/configuration/#cache-dir
**cache-dir**
Type: string
The path to the cache directory used by Poetry.
Defaults to one of the following directories:
* macOS: ~/Library/Caches/pypoetry
* Windows: C:\Users\<username>\AppData\Local\pypoetry\Cache
* Unix: ~/.cache/pypoetry

Also, the cache can be stored in the local repo folder (my_repo\.venv) instead of stored in clearml's cache.

**Comment by bmartinn** [comment]
Thanks @johnml1135 , this is a great to add it, and will save some time spinning a Task.
I think we will automatically add `~/.cache/pypoetry` mapping  into an external cache (host side) like we do with the pip cache.

**Comment by bmartinn** [comment]
Hi @johnml1135 
A fix was pushed to the main branch, I'll update here once an RC is out for testing :)
