### ISSUE TITLE
[Bug | clearml-agent] `clearml-agent daemon --stop` crashes when 'default' queue has been removed

### ISSUE THREAD

**Issue by talajasi7** [allegroai/clearml-agent#80]
If the 'default' queue is accidentally removed from the queue list, the `clearml-agent daemon --stop` command crashes when trying to shut down the active agents in the case no further options are included after `--stop` command. Specifically, I got the following error:

`clearml_agent: ERROR: APIError: code 400/707: No queue is tagged as the default queue for this company`

Also I noticed the problem persists after creating another 'default' queue.

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
