### ISSUE TITLE
Possibility of setting git clone location

### ISSUE THREAD

**Issue by mhashas** [allegroai/clearml-agent#82]
Hi,

Currently when running an HPO, the repository is cloned: /root/.clearml/venvs-builds/3.8/task_repository/repo.git. Would it be possible have this location changeable (or is it already?).

Context: 
I am running an HPO, I have a project with an input parameter --data_dir. I mount the data folder into the correct location. For example (workspace/repo/data/). Now, when loading my data, each file also points to another file in a directory, that has a relative location, i.e. "./data/directory/file2". When running locally everything works as the data_dir and the code are under the same folder.

In the HPO however, my data is in /workspace/repo/data, but the codebase is actually in /root/.clearml/venvs-builds/3.8/task_repository/repo.git. What I would like to be able to do is to tell the agent, hey "CD/create /workspace/repo" and git clone here the repository. 

Is this already possible? If not, do you think its a good idea to add it? It would help me quite a bit

**Comment by bmartinn** [comment]
Hi @mhashas 

> I have a project with an input parameter --data_dir ...

The straightforward answer would be to change the `data_dir` argument on the Task (I'm assuming argparser) `Args/data_dir`  to point to `/workspace/repo/data/` , am I missing something here?
How do you mount the data folder itself ? Can I assume the agent is running in docker-mode?

btw:
you could change the parent folder of the git repo (see [here](https://github.com/allegroai/clearml-agent/blob/6c5087e425bcc9911c78751e2a6ae3e1c0640180/docs/clearml.conf#L193)) but this will not change the sub-folder `./3.8/task_repository/repo.git` ...
