### ISSUE TITLE
Allow specifying which poetry version to use

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml-agent#90]
Much like one can choose which `pip` version to use, it would be great if one could also specify the desired `poetry` version (or have it derived from the incoming task).

**Comment by jkhenning** [comment]
Hi @idantene,

Sounds like a good idea, I'll put it on my tasks list and take a look 🙂

**Comment by idantene** [comment]
I see this was secretly (or maybe not so secretly?)  added with the `package_manager.poetry_version`, thanks!
